### PR TITLE
Remove dependency on mocha-eslint

### PR DESCRIPTION
**Pull request by IanVS**
Instead of using an external dependency, can use npm scripts to accomplish essentially the same result.  This also solves the problem of relying on the version of eslint included in the mocha-eslint module.

With these changes, linting is now run prior to any tests, which will also save time.

### CODE REVIEW

**Comment by Globegitter** [comment]
Interesting idea, let me think about that a bit. 

But regardless I think we should have eslint as a devDependency and then just use that rather than relying on a globally installed one.

And if eslint throws some errors would the tests then fail on Travis?

**Comment by IanVS** [comment]
Agree completely about dev dependency. 

And yes, the linting will exit with a nonzero code and the tests won't even run if there is a linting error, which would cause CI to fail.

**Comment by Globegitter** [comment]
Ok that sounds good - another idea I mentioned to Martin yesterday and had on my mind for a while to make it easy to only run part of the test suite to encourage running `npm test` on your local machine. We have partly done that via `npm test -- lint` but I was thinking to make the `runner.js` into a very simple npm module (since I am using it on a lot of projects now etc.) and make it much more dynamic. 

So when you require it allows you specofy: `npm test -- <filepath>` (without file-ending, test one file directly), `npm test -- <folderName> [fileName or glob]` (Run only part of the test suite: a whole folder and all its subfolders. Optionally select a subset via glob), `npm test -- lint` (what it currently does, but just expecting the file to be in the `unit` folder).

Per default it uses `{unit,acceptance}` but offers an option for custom folders. Probably there should also be a switch for naming conventions (camelCase, dasherized).

This PR does not affect the idea for the most part, just one would be consistency `npm run lint` vs `npm test  -- lint` and this would make linting always run before any tests right? Does it add any 'significant' time (1s+) even if all the files pass?

**Comment by IanVS** [comment]
I will try to profile it in the next few days, but I did not subjectively notice any difference in time.  I think the benefit is that if the linting fails, the tests do not run at all, which in turn saves time.

This PR uses the strategy presented in http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/, and I have seen it in other packages now as well.  The more I think about it, the more I think that linting and testing are two separate things, and there's no real good reason to mix them together.

**Comment by Globegitter** [comment]
Interesting idea, I do like it and it makes a lot of sense. Let's go with it!

**Comment by IanVS** [comment]
It makes me sad to admit that mocha-eslint is not actually useful, but I think this is the right approach.

**Comment by Globegitter** [comment]
Well it makes it as useless as `mocha-jshint`, which is used by ember-cli itself. So seems that at least 
some people put some value in it. And you learned from it.

**Comment by IanVS** [comment]
Yes the learning has been invaluable, for sure.  

I wonder if it would be worthwhile for ember-cli to use the approach in this PR as well...I'll make a PR and see what they say.

**Comment by Globegitter** [comment]
@IanVS Good step into the right direction. Can you just add this as a `devDependency` and update the `lint` script to use the bin in the node_modules folder in a new PR?

**Comment by IanVS** [comment]
ESLint is already a devDependency...not sure what you mean?  Also, using npm scripts automatically uses the local 'node_modules`.  From http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/:

> The npm run shell environment provides lots of helpful features to make sure your scripts are as succinct as they can be. For example the shell's PATH has your ./node_modules/.bin/ folder inside of it, meaning any dependencies you install which have binaries can be called directly from a scripts shell.

**Comment by Globegitter** [comment]
@IanVS ah yeah I did check and somehow missed that. And that is great to know about the shell. Thanks again!

**Pull request merged**
