### PR TITLE
Added babel-eslint

### PR DESCRIPTION
**Pull request by Globegitter**
This is just to get started with https://github.com/artificialio/sane/issues/108. I have just copied the rules from https://github.com/babel/babel/blob/master/.eslintrc and not checked if they all make sense for us, or if we should add more as mentioned here: http://eslint.org/docs/rules/

Performance so far seems decent enough when running `eslint lib/*` (after installing `npm i -g eslint babel-eslint)

I won't be able to carry on working on this for another few days but if @IanVS or @kriswill want a play with it, feel free to go ahead. I think it would be really useful to have all the code linted.

### CODE REVIEW

**Comment by Globegitter** [comment]
Adding a `.eslintignore` will probably also be worth it to improve performance.

**Comment by IanVS** [comment]
I'll give it a shot. Will be a good chance to learn how linters really work.

**Comment by Globegitter** [comment]
Awesome thank you @IanVS! Some possibly interesting read: https://www.drupal.org/node/2264205, http://davidwalsh.name/eslint and http://www.sitepoint.com/comparison-javascript-linting-tools/

**Comment by IanVS** [comment]
@Globegitter I submitted https://github.com/artificialio/sane/pull/115 which integrates ESLint into the mocha tests.  I also modified the .eslintrc somewhat based on the discussions we've had about code style, but I may have gotten some things not to your liking, so feel free to modify of course.

**Comment by Globegitter** [comment]
Closing in favour of #115

**Comment by IanVS** [comment]
#115 is a pull request into the eslint branch, so I think you're still going to need this PR to get the changes into master.  I was trying to avoid stomping on the work you had already done here.

**Comment by Globegitter** [comment]
aahh yes. You are quite right.

**Comment by Globegitter** [comment]
Thank you for the PR @IanVS - I just gave you contribution rights so we can both work on this branch to fix all the lint errors. Probably will get to it tomorrow.

**Comment by Globegitter** [comment]
Any idea why windows is failing?

**Comment by Globegitter** [comment]
You mean remove the quotes and use the helper you wrote a while ago?

**Comment by IanVS** [comment]
That's my guess / suggestion. I can't try until tonight.

**Comment by IanVS** [comment]
@Globegitter Why doesn't Node 0.12 like the backticks in mocha-eslint, whereas iojs is okay with them?

**Comment by Globegitter** [comment]
Node 0.12 only supports back ticks with a flag I believe. Probably easiest to just use normal strings.

**Pull request merged**
