### PR TITLE
Add .hbs extension to handlebars template files

### PR DESCRIPTION
**Pull request by IanVS**
Also simplify template renaming with regex.  Assumes underscore should only be at beginning of filename.  Previous method would have split on interior underscore, not sure that was intended.

### CODE REVIEW

**Comment by kriswill** [comment]
why do we need this?

**Comment by IanVS** [comment]
Just for consistency. @globegitter told me it's a convention he's following to indicate files that use  handlebars.

**Comment by kriswill** [comment]
why not use `filename.ext.hbs`?  I think that makes more sense if they are handlebars template files.

**Comment by Globegitter** [comment]
Actually that is a good idea. Then we would need to update the helpers as well. @IanVS I would be happy to merge since we discussed, but what do you think of @kriswill's suggestion? Could you update to that?

**Comment by IanVS** [comment]
I agree that it would be more clear to use .hbs extensions. I will update the PR.

**Comment by IanVS** [comment]
This was a test of my ability to rebase and squash, but I think it worked correctly.

**Comment by Globegitter** [comment]
Thank you a bunch for that @IanVS. Consistency changes feel so rewarding :)

**Pull request merged**
