### PR TITLE
Fix tests on Windows / Appveyor

### PR DESCRIPTION
**Pull request by IanVS**
Attempt to get tests to pass on Windows machines.  Still having
some trouble with line endings in assertFileEquals, but all other
tests are passing.

Implemented superspawn to replace child-process-promise, and added
a 'sane.cmd' file to allow execution on Windows.

### CODE REVIEW

**Comment by kriswill** [comment]
Looks like superspawn is using `child_process.spawn` with `cmd /s /c sane.cmd` and cloning the `process.env` into the cmd.  We might be able to do the same thing without the extra dependency.  Nice find!

**Comment by kriswill** [comment]
I'm going to go ahead and merge this, since this is the first time appveyor tests are passing.  it will set the baseline for ensuring all tests pass before accepting PRs.

**Comment by Globegitter** [comment]
Thanks @kriswill Yeah I think that was a good move, just haven't had time yet to review the code to merge it in.

**Comment by IanVS** [comment]
Woohoo, my first merged pull request!

**Pull request merged**
