### PR TITLE
Use ember installed in client instead of relying on global

### PR DESCRIPTION
**Pull request by okket**

### CODE REVIEW

**Comment by Globegitter** [comment]
Thanks for getting on this quite quickly.

The path should be `client/node_modules/ember-cli/bin` though and could you use `path.join` as well as do the same for windows?

**Comment by IanVS** [comment]
@okket It looks like the test for `generate` is failing, because generation occurs within the client folder: https://github.com/artificialio/sane/blob/master/lib/commands/generate.js#L48

**Comment by okket** [comment]
Yes, I am looking to both. 

```sails g resource user name:string age:number``` did work for me without error / global ember.

**Comment by okket** [comment]
I don't know why the test fails. The cwd in spawn is not considered for looking up the executable.

**Comment by Globegitter** [comment]
@okket It might be a missing `node_modules` folder. Also not sure if it has issues with the folder it currently is - it does produce an absolute path with `process.cwd()` right? But in any case, I can have a proper look maybe tomorrow.

**Comment by IanVS** [comment]
Perhaps it's better to use `__dirname` rather than `process.cwd`, since `process.cwd` depends on where the command is called from.  See http://www.hacksparrow.com/understanding-directory-references-in-node-js.html for a better explanation.

**Comment by okket** [comment]
```sane generate``` et. al. should (can?) only be called from the project root directory. A function like ```process.cwd``` that gives back the directory from where command/process was called from is exactly what we need here.

Except there is a better way to call a binary from a node script that spawns a new node process. Is this really the canonical / best way to interact?

**Comment by Globegitter** [comment]
@okket Yeah I have been thinking about that as well - if there is a better way to do it. Since we now purely rely on the local ember-cli we could consider just `requiring` it.

**Comment by IanVS** [comment]
@okket you're absolutely right, sorry.  It seems the actual problem is that when the tests are run, the tmp project that is created is done so with --skip-npm, so ember doesn't actually exist locally for the test.

**Comment by Globegitter** [comment]
Oh yes @IanVS , that is a very good point I did not think about. 

Hmm, will have to think about how to do this best. I would be good to just have to install ember-cli once for all tests and require/spawn it then. I think I remember reading something over at ember-cli with caching node_modules for their tests.

**Comment by Globegitter** [comment]
One thing I can think off is to add a unit-test for `lib/helpers/ember.js` to make sure the path is always correct and then have a new `ember.js` helper in `tests/helpers` that uses the global ember, at least for a quick-fix.

**Comment by Globegitter** [comment]
@okket What do you think of the above mentioned workaround?

Otherwise, http://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/ and blog.clevertech.biz/post/faster-node-js-builds-with-travis-ci seems worth considering as well. We could just manually `npm install ember-cli` within the test after the app has been setup. But then not sure if caching would work, since https://github.com/kaelzhang/node-tmp-sync creates new tmp-dirs for all tests.

**Pull request closed without merging**
