### PR TITLE
upgrade node to 0.12 - remove support for old node

### PR DESCRIPTION
**Pull request by kriswill**
no need to support 0.10 or 0.11 of node, they are replaced completely by current node stable 0.12.

### CODE REVIEW

**Comment by kriswill** [comment]
Appveyor is B.S.  looks like they have blessed versions of node and io.js they know about.

**Comment by kriswill** [comment]
looks like Appveyor's node-gyp is messed up.  it cannot build the necessary binaries for child_process to function properly.  So, we're seeing these in the test output:
```sh
1) Acceptance: sane generate resource/api user:
     Error: spawn C:\projects\sane\bin\sane ENOENT `C:\projects\sane\bin\sane new . --skip-npm --skip-bower --skip-analytics` (exited with error code ENOENT)
      at exports._errnoException (util.js:738:11)
      at Process.ChildProcess._handle.onexit (child_process.js:1019:32)
      at child_process.js:1109:20
      at process._tickCallback (node.js:337:11)
```

**Comment by kriswill** [comment]
Doh, windows doesn't know `#!/usr/bin/env node` she-bang binaries.  We'll need to create a sane.bat for the windows platform, so we can call child_process.spawn.

**Comment by Globegitter** [comment]
@kriswill aahh that is a good point. But how is ember-cli doing it? They are not having an ember.bat. Maybe I'll get some more time tonight to check that out https://github.com/ember-cli/ember-cli/issues/1558. That seems to have some interesting pointers.

**Comment by Globegitter** [comment]
Aahhh, because we are using `execFile`. Yeah that might be the issue.

**Comment by kriswill** [comment]
@Globegitter take a look at ember-cli's new test here: https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/new-test.js#L81-L91 

Instead of forking a child process they simply call the ember-cli processor with arguments, and use a promise to check the results.

**Pull request merged**
