### PR TITLE
Fix ENOENT error on Windows

### PR DESCRIPTION
**Pull request by IanVS**
Error was due to windows not being able to execute plain "sails" and
"ember", and instead needing "sails.cmd" and "ember.cmd"

See http://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err
for more background

### CODE REVIEW

**Comment by kriswill** [comment]
Where is `sails.cmd` coming from?  Is it something NPM does on windows?

**Comment by IanVS** [comment]
Yes, it is a Windows executable batch file that npm creates which basically just tells Windows how to run the real sails executable.

**Comment by Globegitter** [comment]
Awesome @IanVS, thanks for that! Do you think you could remove `superspawn` from the dependencies as well as from the `new` and `generate` command and update to use the `.bat` files?

Also if you could fix the appveyor tests that way, that would be great.

**Comment by IanVS** [comment]
Sure, I'll take a shot at it.  For reference, here is the issue in Node causing this headache: https://github.com/joyent/node/issues/2318

**Comment by IanVS** [comment]
Turns out I'm having difficulty removing superspawn, which also does some nice things like return promises.  It would probably take a larger refactor to remove it, and my first attempts have failed so far.  

I was able to get the tests to pass in Appveyor, but I had to resort to using superspawn there as well.  So, hopefully this PR is still useful to enabling Windows support.  Maybe I can try removing superspawn at a later time. I'm still just learning JavaScript, and I don't develop on Windows, so honestly I'd rather spend my time learning to use sails and ember to build cool things.

**Comment by oalbrecht** [comment]
Hi Ian,

No problem! Thanks so much for all the work you put in trying to get it to
work on Windows. I might go ahead and install linux on my computer and
hopefully I'll have better luck with Sane there.

All the best,

Oliver

**Comment by IanVS** [comment]
@oalbrecht, I posted a few comments to you in the gitter chat.  I saw you tried to clone my repo and test it out, thanks for that.  I think the problem is that when you run `sane new` a copy of sane-cli is pulled from npm and put into the node_packages directory, and then once you're inside your project any `sane` commands you run use that version (instead of your global version linked from the git clone).  So, if you delete the node_modules/sane-cli/bin directory, it should fall back to your global version.  Also, make sure you have the fix_up-on-windows branch checked out, as that is where these fixes were made.  Please let me know if that helps.

**Comment by oalbrecht** [comment]
Yeah, I never deleted the node_modules/sane-cli/bin. Though I guess based
on what you said earlier, it still shouldn't work 100%, right? ("Turns out
I'm having difficulty removing superspawn, which also does some nice things
like return promises. It would probably take a larger refactor to remove
it, and my first attempts have failed so far.").

**Comment by IanVS** [comment]
@oalbrecht no, it should work fine as-is.  That comment was aimed at removing a dependency (cleaning up the code), not enabling functionality.

**Comment by IanVS** [comment]
Sorry for the messy commit history, my git skills are not so great.

If this is merged, https://github.com/artificialio/sane/pull/79 will have to be reworked to remove superspawn.

**Comment by oalbrecht** [comment]
Oh okay, cool. I'll try to test your changes tonight.

Thanks again,

Oliver

**Comment by Globegitter** [comment]
Don't worry about the commits @IanVS. The most important thing is you are getting the grips of everything ;) So this should now completely fix windows (apart from the tests) without superspawn?

**Comment by IanVS** [comment]
@globegitter, I believe so. It would be good if @oalbrecht can independently test and verify everything works.

**Comment by oalbrecht** [comment]
@IanVS It works! Like you had recommended, I deleted the node_modules/sane_cli/bin directory, then ran "sails up" and the server and client both started correctly.

**Comment by Globegitter** [comment]
Awesome @IanVS is this now ready to merge from your side?

**Comment by IanVS** [comment]
Yes.

**Comment by Globegitter** [comment]
Thank you. We finally have windows support!

**Comment by oalbrecht** [comment]
Hurray! Nice job @IanVS!

**Pull request merged**
