### PR TITLE
Fix appveyor config to check for node module cache dir before creation

### PR DESCRIPTION
**Pull request by kriswill**
check for path first

### CODE REVIEW

**Comment by kriswill** [comment]
Now it fails because it's taking too long to run.  I think the limit is 40 minutes.

**Comment by IanVS** [comment]
Oh good grief.  We really need to clean up the tests, that's ridiculous.  Should we just merge it?

**Comment by kriswill** [comment]
I'd say merge it. At least it make's the run less broken.  The longer term fix is to make the tests faster, and that means reducing the number of files that it's writing to disk.  The way the tests are spawning child processes is not a very good design, and they should be grouped under a "slow" flag.  Any tests that don't write files to disk should be considered "fast" and suitable for running on any CI.

**Comment by IanVS** [comment]
Agreed.  Thank you.

**Pull request merged**
