### PR TITLE
Prevent /server files being owned by root on linux

### LINKED ISSUE #70: On sane new: EACCES, permission denied 'server/.sailsrc'
I'm new to sane, so maybe I'm doing something wrong, but when I try to run `sane new project --docker` I receive the following:

      create tests/.jshintrc
      create tests/helpers/resolver.js
      create tests/helpers/start-app.js
      create tests/index.html
      create tests/test-helper.js
      create tests/unit/.gitkeep
      create vendor/.gitkeep
    Installed packages for tooling via npm.
    Installed browser packages via Bower.
    Running tooling scrips for Sane....EACCES, permission denied 'server/.sailsrc'
    Running tooling scrips for Sane...

and the foldersize sits at 190M, so I'm guessing it's hung up.  The entire `server/` folder is owned by root, whereas it is owned by my user when I `sane new project` without docker.

I am using:

    sane: 0.0.23
    fig: 1.0.1
    docker: 1.5.0, build a8a31ef

and I have DOCKER_HOST set as suggested in https://gist.github.com/RuslanHamidullin/94d95328a7360d843e52

### PR DESCRIPTION
**Pull request by IanVS**
Fixes #70.  Tested on Linux, please test on OSX and Windows.

I can try to add acceptance tests, but I'm pretty new to it and not sure exactly how I would go about it.

### CODE REVIEW

**Comment by Globegitter** [comment]
That looks great thank you. The only thing I am a bit surprised about is that `npm install` needs root. I will test again on my ubuntu machine before merging, just checking what is needed in that regards.

**Comment by IanVS** [comment]
I'm guessing it has to do with how npm was installed on the Docker container.  If I don't reset the fig.yml and instead try to npm install as a normal user, this is what I get:

    Installing Sails packages for tooling via npm.fig: Command failed with exit code 3 Error output:
    npm ERR! Linux 3.13.0-24-generic
    npm ERR! argv "node" "/usr/local/bin/npm" "i" "sails-generate-ember-blueprints" "lodash@^2.4.1" "morgan" "pluralize" "sails-disk" "--save"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.1.16
    npm ERR! path /.npm
    npm ERR! code EACCES
    npm ERR! errno 3

    npm ERR! Error: EACCES, mkdir '/.npm'
    npm ERR!  { [Error: EACCES, mkdir '/.npm'] errno: 3, code: 'EACCES', path: '/.npm', parent: 'server' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /server/npm-debug.log

**Comment by Globegitter** [comment]
Hmmm, I am not happy with this situation. Npm should not get installed as root in the first place and you should not have to run `npm i` as a root. I'll probably merge this in as-is anyway. Since a solution is better than no solution.
And again thank you for the effort, really appreciate this.

**Comment by IanVS** [comment]
I agree that npm shouldn't be installed as root, but that's how it is installed in the dockerfile of the node:slim that is the base of your docker-sails dockerfile.  Sorry, my grasp on docker terminology is pretty week, so hopefully you get what I'm saying.

Here's a link to that dockerfile: https://github.com/joyent/docker-node/blob/c04479fd0117c59d31e426a500ad4f5dd2399f19/0.12/slim/Dockerfile

Someone in the comments asked why a non-root user wasn't used instead, but got no reply.  Maybe the next step would be to create a custom dockerfile which installs node and npm as non-root.

On another note, I am finishing up a PR to fig to enable it to be run with a specified user.  If that goes through, this PR could likely be made a lot simpler.  However, they also changed the name "fig" to "docker-compose" so there might be more work involved to start using the latest version.

**Comment by Globegitter** [comment]
That is a good point. Also now thinking about it, having an acceptance test for docker would be very good. I am starting to clean up and slightly improve the tests here: https://github.com/artificialio/sane/tree/addon-system/tests/acceptance.

Actually now thinking about it, the coming enhancements will add a `sane install` command, which amongst other things will allow you to install npm packages in your docker container. This is then ideal to test this code. So this will get merged first and then you could make another PR to write a test, once the addon-system branch lands.
I am more than happy to give you a couple of pointers for the tests.

**Comment by IanVS** [comment]
https://github.com/docker/fig/pull/971 is the PR for specifying the user directly.  If that is accepted, I'll make another sane PR which will simplify matters greatly.

I'll be more than happy to try to make some tests when the time comes.

**Comment by Globegitter** [comment]
Thank you for the fix.

**Pull request merged**
