### PR TITLE
[BUGFIX] Fix whitespace linting errors

### PR DESCRIPTION
**Pull request by IanVS**
Not sure why these were passing before...

### CODE REVIEW

**Comment by IanVS** [comment]
@globegitter, very strange behavior in the iojs Travis build. Somehow comparing node version to ember version.

**Comment by Globegitter** [comment]
@IanVS yep, I have seen this behaviour on nodejs 0.10.x before. Will investigate today,

**Comment by Globegitter** [comment]
Might also be worth to test iojs 1.x 2.x separately.

**Comment by IanVS** [comment]
I can't test it, but I'm guessing the problem is due to this: https://github.com/artificialio/sane/blob/master/src/commands/new.js#L204 Maybe there's a better way than scraping the output of `ember --version`?  I'll do some research.

**Comment by IanVS** [comment]
@Globegitter Sorry for all the commits, trying to dev on github.com without an editor, linter, or command line...

At any rate, from what I can tell, in Travis, the directory `/home/travis/build/artificialio/sane/node_modules/.bin/ember` is added to the PATH environment variable and is picked up by `emberExists`.  That's why it never failed before, even though ember-cli is not globally installed in Travis and everyone trying to install sane-cli without ember-cli would run into problems.

I'll try to break this into two separate commits and/or PRs, since this PR is now doing more than just fixing linting errors.

**Comment by IanVS** [comment]
Getting in just the linting fixes for now, will open a subsequent PR with the other fixes.

**Comment by IanVS** [comment]
https://github.com/artificialio/sane/pull/159 created.

**Comment by Globegitter** [comment]
:+1:

**Pull request merged**
